services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  webapi:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__Postgres: "Host=postgres;Database=mydb;Username=myuser;Password=mypassword"
      Redis__Connection: "redis:6379"
    depends_on:
      - postgres
      - redis

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - RI_APP_PORT=8001
    depends_on:
      - redis

volumes:
  postgres_data:
